#!/usr/bin/env python
import sys
import re
import subprocess

errors = 0


def report_error(message, condition=True):
    global errors
    if condition:
        print("\n COMMIT MESSAGE ERROR:")
        print("==========================")
        print(message)
        errors += 1


modified_msg = ""
msg_file = sys.argv[1]
with open(msg_file) as file:
    message = file.readlines()

# Check that the subject line is limited to 120 characters
if len(message[0]) > 120:
    report_error('Limit the subject line to 120 characters (Current is: {})'.format(
        len(message[0])))

# Check that the subject line is capitalized
if message[0][0].islower():
    report_error('Capitalize the subject line')

# Check that the subject line doesn't end with a period
if message[0].strip()[-1] == '.':
    report_error('Do not end the subject line with a period')

# Check that the second line is empty
if len(message) > 1 and len(message[1].strip()) > 0:
    report_error('Leave the second line empty')

# Check that the third line is not empty
if len(message) <= 2 or len(message[2].strip()) == 0:
    report_error('Use the body to explain what and why')

with open(msg_file, 'w') as file:
    file.write(modified_msg)

gitProcess = subprocess.Popen(['git', 'diff', '--cached'], stdout=subprocess.PIPE)
gitOutput = str(gitProcess.communicate()[0])
if 'NOCOMMIT' in gitOutput.upper():
    report_error('The commit contains the string "NOCOMMIT" -- looks like you forgot something')

exit(errors)
